### ISSUE TITLE
Converting a 8x8 square with multiple physical groups

### ISSUE THREAD

**Issue by essicolo** [iitrabhi/meshx#2]
Hi, I tried to convert [this mesh](https://gist.github.com/essicolo/0067225e65db25b3b5a86343a5981820) from gmsh to xdmf.

```
meshx square_subdomains.msh
```

I got this error.

```
String tag      Num Tag    Dim
------------  ---------  -----
left                  8      1
right                 9      1
bottom               10      1
top                  11      1
domainbottom         12      2
domaintop            13      2
Creating gmsh:physical mesh
There was some error 😱
Traceback (most recent call last):
  File "/opt/conda/bin/meshx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/meshx/_cli.py", line 13, in main
    write(args)
  File "/opt/conda/lib/python3.7/site-packages/meshx/_helpers.py", line 13, in write
    converter.write_sub_domains()
  File "/opt/conda/lib/python3.7/site-packages/meshx/_helpers.py", line 86, in write_sub_domains
    infile.read(mesh)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "mesh/line.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  76bf12b24408e3ce2364eb22e62c802a92c90ff2
*** -------------------------------------------------------------------------
```

**Comment by iitrabhi** [comment]
I am unable to recreate the problem on my system. Can you please check with the docker file mentioned in readme. All the dependencies are written in that docker file.
